version: '3.7'

services:

  postgres:
    image: postgres:15.4-alpine3.18
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 256M
    ports:
      - 5432:5432
    networks:
      - postgres_network2
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres-data2:/var/lib/postgresql/data

  simplecrud:
    image: alhon05/golangsimplecrud:v${VERSION}
    volumes: 
      - simplecrud_data:/services/simplecrud
    ports:
      - 4005:4005
    networks:
      - postgres_network2
    depends_on:
      - postgres

volumes:
  postgres-data2:
  simplecrud_data:

networks:
  postgres_network2:



